{{- if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: syncpocalypse
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: syncpocalypse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: "LOG_LEVEL"
              value: {{ .Values.logLevel }}
      restartPolicy: {{ .Values.restartPolicy }}
  backoffLimit: {{ .Values.backoffLimit }} # Commenting this as it deletes the Pod after the backoffLimit is reached and no alert can be created
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }} # Keep the job for after completion
{{- end }}
